<a href="https://colab.research.google.com/github/hassankirwa/NumPy/blob/master/Dive_into_deep_learning_d2l.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
pip install mxnet-cu101==1.7.0


     |███████████████████████████████▌| 834.1MB 1.3MB/s eta 0:00:10tcmalloc: large alloc 1147494400 bytes == 0x65c8a000 @  0x7f3d4c57b615 0x591f47 0x4cc229 0x4cc38b 0x50a51c 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50cfd6 0x58e793 0x50c467 0x58e793 0x50c467 0x58e793 0x50c467 0x58e793 0x50c467 0x509918 0x50a64d 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x509918 0x50a64d
     |████████████████████████████████| 846.0MB 20kB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


In [5]:
from mxnet import np, npx
npx.set_np()

In [6]:
#create a row vector x containing the first 12 integers starting with 0
x = np.arange(12)

In [7]:

x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [8]:
# we can access a tensor's shape
x.shape

(12,)

In [9]:
#If we just want to know the total number of elements in a tenso
x.size

12

In [10]:
#To change the shape of a tensor without altering either the 
#number of elements or their values, we can invoke the reshape function.
X = x.reshape(3,4)
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [11]:
#We can create a tensor representing a tensor with all elements set to 0 and a shape of (2, 3, 4) as follows:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
# create a tensor with with each element sampled from a Standard Gaussian(normal)distribution
np.random.normal(0, 1, size= (3,4))

array([[ 2.2122064 ,  1.1630787 ,  0.7740038 ,  0.4838046 ],
       [ 1.0434403 ,  0.29956347,  1.1839255 ,  0.15302546],
       [ 1.8917114 , -1.1688148 , -1.2347414 ,  1.5580711 ]])

In [14]:
# We can also specify the exact values for each element in the 
#desired tensor by supplying a Pythonlist (or list of lists) containing the numerical values
np.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [15]:
# Elementwise operations
x = np.array([1,2,4,8])
y = np.array([2,2,2,2])
x+y, x-y, x*y, x/y , x ** y #The ** operator is exponentiation


(array([ 3.,  4.,  6., 10.]),
 array([-1.,  0.,  2.,  6.]),
 array([ 2.,  4.,  8., 16.]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1.,  4., 16., 64.]))

In [16]:
# we can concatenate multiple tensors together
# axis 0 = along the rows
# axis 1 = columns

X = np.arange(12).reshape(3,4)
Y = np.array([[2,1,4,3], [1,2,3,4],[4,3,2,1]])
np.concatenate([X,Y],axis = 0) ,np.concatenate([X,Y], axis = 1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
# constructing a binary tensor via logical statements
X == Y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [18]:
# summing all the elements in a tensor yields a tensor with one element
X.sum()

array(66.)

In [19]:
# broadcasting mechanism
a = np.arange(3).reshape(3,1)
b = np.arange(2).reshape(1,2)
a,b

(array([[0.],
        [1.],
        [2.]]), array([[0., 1.]]))

In [20]:
# the shapes do not much up so we do broadcast the entries of both matrices into a larger 3 * 2 matrix 
#matrix a replicates columns ,matrix b replicates rows
a + b

array([[0., 1.],
       [1., 2.],
       [2., 3.]])

In [21]:
# indexing and Slicing
X[-1],X[1:3]

(array([ 8.,  9., 10., 11.]), array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]))

In [22]:
# we can also write elements of a matrix by specifying indices
X[1,2]= 9
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]])

In [23]:
X[0:2, :] = 12
X

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]])

In [24]:
#Saving Memory
before = id(Y)
Y = Y + X
id(Y) == before

False

In [25]:
# Converting to a Numpy tensor or viceversa 
A = X.asnumpy()
B = np.array(A)
type(A),type(B)

(numpy.ndarray, mxnet.numpy.ndarray)

In [26]:
# to convert a size -1 tensor to a python scalar ,we inveoke the item function 
#or built in functions
a = np.array([3.5])
a, a.item(),float(a), int(a)

(array([3.5]), 3.5, 3.5, 3)

In [27]:
# Data processing
#Reading the Dataset
import os



def mkdir_if_not_exist(path):    #@save
    if not isinstance(path, str):
       path = os.path.join(*path)
    if not os.path.exists(path):
       os.makedirs(path)




 

In [28]:
data_file = '../data/house_tiny.csv'
mkdir_if_not_exist('../data')
with open(data_file,'w') as f:
  f.write('NumRooms,alley,prince\n') #column names
  f.write('NA,Pave,127500\n') # Each row represents a data example
  f.write('2,NA,106000\n')
  f.write('4,NA,178100\n')
  f.write('NA,NA,14000\n')   


In [29]:
import pandas as pd 

data = pd.read_csv(data_file,engine="python" ,)
print(data)

   NumRooms alley  prince
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN   14000


In [30]:
#handling missing data
inputs, outputs = data.iloc[:,0:2],data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [31]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  alley_Pave  alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [32]:
# conversion to the Tensor format 
from mxnet import np

X, y = np.array(inputs.values), np.array(outputs.values)
X,y

(array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=float64),
 array([127500, 106000, 178100,  14000], dtype=int64))

In [33]:
# linear algebra
#scalars 
from mxnet import np,npx
npx.set_np()
x = np.array(3.0)
y = np.array(2.0)

x + y, x * y, x/y, x **y


(array(5.), array(6.), array(1.5), array(9.))

In [34]:
#Vectors
x = np.arange(4)
x

array([0., 1., 2., 3.])

In [35]:
x[3]

array(3.)

In [36]:
#length ,Dimentionality and shape
len(x)

4

In [37]:
x.shape

(4,)

In [38]:
#Matrices

A = np.arange(20).reshape(5,4)
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [39]:
A.T

array([[ 0.,  4.,  8., 12., 16.],
       [ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.]])

In [40]:
B = np.array([[1,2,3],[2,0,4],[3,4,5]])
B

array([[1., 2., 3.],
       [2., 0., 4.],
       [3., 4., 5.]])

In [41]:
B == B.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [42]:
# Tensors
X = np.arange(24).reshape(2,3,4)
X

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [43]:
#tensor arithmetic operations
A = np.arange(20).reshape(5,4)
B = A.copy()  #Assign a copy of 'A' to 'B' by allocating new memory
A, A + B

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]), array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]]))

In [44]:
A * B

array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.],
       [256., 289., 324., 361.]])

In [45]:
a = 2
X = np.arange(24).reshape(2,3,4)
a + X,( a * X).shape

(array([[[ 2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.]],
 
        [[14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.]]]), (2, 3, 4))

In [46]:
# reduction
X =np.arange(4)
X, x.sum()

(array([0., 1., 2., 3.]), array(6.))

In [47]:
A.shape, A.sum()

((5, 4), array(190.))

In [48]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(array([40., 45., 50., 55.]), (4,))

In [49]:
A.sum(axis=[0,1]) #Same as 'A.sum()'

array(190.)

In [50]:
A.mean(),A.sum()/A.size

(array(9.5), array(9.5))

In [51]:
A.mean(axis=0),A.sum(axis=0) /A.shape[0]

(array([ 8.,  9., 10., 11.]), array([ 8.,  9., 10., 11.]))

In [52]:
# Non-reaductionSum
sum_A= A.sum(axis=1,keepdims=True)
sum_A

array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]])

In [53]:
A / sum_A

array([[0.        , 0.16666667, 0.33333334, 0.5       ],
       [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
       [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
       [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
       [0.22857143, 0.24285714, 0.25714287, 0.27142859]])

In [54]:
#cumulative sum
A.cumsum(axis=0)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  6.,  8., 10.],
       [12., 15., 18., 21.],
       [24., 28., 32., 36.],
       [40., 45., 50., 55.]])

In [55]:
# DOT PRODUCTS
y =np.ones(4)
x,y,np.dot(x, y)

(array([0., 1., 2., 3.]), array([1., 1., 1., 1.]), array(6.))

In [56]:
np.sum(x*y)

array(6.)

In [57]:
#matrix vector product
A.shape,x.shape,np.dot(A,x)

((5, 4), (4,), array([ 14.,  38.,  62.,  86., 110.]))

In [58]:
#matrix multiplication
B = np.ones(shape=(4,3))
np.dot(A,B)

array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]])

In [59]:
#Norms
u = np.array([3, -4])
np.linalg.norm(u)

array(5.)

In [60]:
np.linalg.norm(np.ones((4,9)))

array(6.)

In [61]:
pip install d2l

In [62]:
!pip install IPython

In [63]:
# Calculus
# Derivatives and Defferitiantion
%matplotlib inline
from d2l import mxnet as d2l
from IPython import display
from mxnet import np,npx
npx.set_np()

def f(x):
  return 3 * x ** 2 - 4 * x

In [66]:
def numerical_lim(f, x, h):
  return (f(x+h) - f(x)) / h
 
  h = 0.1
  for i in range(5):
    print(f'h={h:.5f}, numerical limit={numerical_lim(f, 1, h):.5f}')
    h *= 0.1

In [68]:
def numerical_lim(f, x, h):
  return (f(x+h) - f(x)) / h 
  h=10
  for i in range(5):
    print (f'h={h:.5f}, numerical limit={numerical_lim(f,1, h):.5f}') 
    h*=10